// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package testcore

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

const (
	IdxParamAddress         = 0
	IdxParamAgentID         = 1
	IdxParamCaller          = 2
	IdxParamChainID         = 3
	IdxParamChainOwnerID    = 4
	IdxParamContractCreator = 5
	IdxParamContractID      = 6
	IdxParamCounter         = 7
	IdxParamHash            = 8
	IdxParamHname           = 9
	IdxParamHnameContract   = 10
	IdxParamHnameEP         = 11
	IdxParamHnameZero       = 12
	IdxParamInt64           = 13
	IdxParamInt64Zero       = 14
	IdxParamIntValue        = 15
	IdxParamName            = 16
	IdxParamString          = 17
	IdxParamStringZero      = 18
	IdxParamVarName         = 19
	IdxResultChainOwnerID   = 20
	IdxResultCounter        = 21
	IdxResultIntValue       = 22
	IdxResultMintedColor    = 23
	IdxResultMintedSupply   = 24
	IdxResultSandboxCall    = 25
	IdxStateCounter         = 26
	IdxStateHnameEP         = 27
	IdxStateInts            = 28
	IdxStateMintedColor     = 29
	IdxStateMintedSupply    = 30
)

const keyMapLen = 31

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAddress,
	ParamAgentID,
	ParamCaller,
	ParamChainID,
	ParamChainOwnerID,
	ParamContractCreator,
	ParamContractID,
	ParamCounter,
	ParamHash,
	ParamHname,
	ParamHnameContract,
	ParamHnameEP,
	ParamHnameZero,
	ParamInt64,
	ParamInt64Zero,
	ParamIntValue,
	ParamName,
	ParamString,
	ParamStringZero,
	ParamVarName,
	ResultChainOwnerID,
	ResultCounter,
	ResultIntValue,
	ResultMintedColor,
	ResultMintedSupply,
	ResultSandboxCall,
	StateCounter,
	StateHnameEP,
	StateInts,
	StateMintedColor,
	StateMintedSupply,
}

var idxMap [keyMapLen]wasmlib.Key32
